default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: poc_teste
  password: x
  host: localhost

development:
  <<: *default
  database: poc_api_development

test:
  <<: *default
  database: poc_api_test

production:
  <<: *default
  database: poc_api_production
